use HeartyHearthDB
go 

grant execute on MeasurementGet to approle
grant execute on CourseGet to approle
grant execute on CuisineDeleteAll to approle
grant execute on RecipeIngredientDelete to approle
grant execute on RecipeDirectionDelete to approle
grant execute on RecipeList to approle
grant execute on DashboardGet to approle
grant execute on RecipeListGet to approle
grant execute on MealListGet to approle
grant execute on CookbookGet to approle
grant execute on CloneRecipe to approle
grant execute on RecipeGet to approle
grant execute on RecipeClone to approle
grant execute on CuisineGet to approle
grant execute on RecipeSummaryGet to approle
grant execute on UsersGet to approle
grant execute on RecipeCookbookGet to approle
grant execute on CookbookUpdate to approle
grant execute on RecipeRecipeDirectionGet to approle
grant execute on RecipeIngredientUpdate to approle
grant execute on RecipeDelete to approle
grant execute on CuisineDelete to approle
grant execute on RecipeDirectionUpdate to approle
grant execute on RecipeCookbookUpdate to approle
grant execute on RecipeCookbookDelete to approle
grant execute on CookbookDelete to approle
grant execute on ChangeRecipeStatus to approle
grant execute on RecipeUpdate to approle
grant execute on CuisineUpdate to approle
grant execute on MealCalories to approle
grant execute on RecipeDesc to approle
grant execute on IsRecipeDeleteAllowed to approle
grant execute on RecipeIngredientGet to approle
grant execute on RecipeDirectionGet to approle
grant execute on CookBookListGet to approle
grant execute on IngredientGet to approle
grant execute on MesurementGet to approle